[project]
name = "v-extra-example"
version = "1.0.0"
requires-python = ">=3.9"

[project.optional-dependencies]
v0 = ["typing_extensions"]

[build-system]
requires = ["hatchling >= 1.26"]
build-backend = "hatchling.build"
